### ISSUE TITLE
Issues when trying out test environment with navrep

### ISSUE THREAD

**Issue by sbuc0005** [ethz-asl/navrep#1]
Hi, so I've tried installing navrep and testing out this environment with the pretrained models in your repository- I have a couple issues that I was wondering about?
I've tried first updating any dependencies and I don't have permission to clone anything (e.g. deep_social_planner, etc).

Also, I run intro a strange issue where "dynamic module does not define module export function (PyInit__tf2) when trying out the test environment with navrep. It appears to be an issue due to the installed ros version being only compatible with python2.7?

Please let me know of your thoughts. Thanks

**Comment by luxiaojuntokyo** [comment]
hi guys:
I install this package following the readme.md
Error comes when I run "pip install navrep", the error is:

RROR: Command errored out with exit status 1:
   command: /home/myname/navrepvenv/bin/python /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb091f29w
       cwd: /tmp/pip-install-e6diedzd/navrep
  Complete output (1 lines):
  /home/myname/navrepvenv/bin/python: can't find '__main__' module in '/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/myname/navrepvenv/bin/python /usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpb091f29w Check the logs for full command output.

Did you encounter this error? Can you give me any suggestion.
Thank you.

**Comment by danieldugas** [comment]
Sorry, somehow missed the notification for this issue.

@sbuc0005 
Not entirely clear what steps you've tried and have failed?

There should be no need to update dependencies, on my end I just run the commands in the Pre-requisite and Install sections and it installs the python code to the environment.

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install -y python3.6 python3.6-dev
sudo apt-get install -y virtualenv python3-virtualenv
virtualenv ~/navrepvenv --python=python3.6
source ~/navrepvenv/bin/activate
pip install --extra-index-url https://rospypi.github.io/simple/ rospy rosbag tf tf2_ros
pip install navrep
```

I assume you are trying to run the ros node for navrep, but are getting system-dependent errors which I'm afraid I cannot help you with. There are some tricky dependency issues with using python 3 with ROS, as indicated by your error message.

Usually, you need to make sure that your python environment contains only the ROS python packages which match the python version, so in this case the ones installed with the command 

```
pip install --extra-index-url https://rospypi.github.io/simple/ rospy rosbag tf tf2_ros
```

but ROS usually adds its python2 packages to the PYTHONPATH when you source /opt/ros/whatever, which can shadow those. Try removing them from the PYTHONPATH?

**Comment by danieldugas** [comment]
@luxiaojuntokyo I have not seen that error.

seems to be the same as here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954256

**Comment by danieldugas** [comment]
Closing, @sbuc0005 feel free to reopen if you have more information about what exactly you are attempting to do and is failing.
