### ISSUE TITLE
test in ianenv

### ISSUE THREAD

**Issue by Yuanzizizi** [ethz-asl/navrep#3]
Hi, thanks for the code. I think your work is interesting and I am following your papers (soadrl, navrep and navdreams). There seems to be no checkpoint file for soadrl (where can I download this: soadrl/Final_models/angular_map_full_FOV). Could you please offer it to me for testing?

Thank you and wait for your reply~

**Comment by CAI23sbP** [comment]
@danieldugas @ethzasl-jenkins same issue about https://github.com/ethz-asl/navrep/issues/5

**Comment by danieldugas** [comment]
Oh, I'm sorry I missed this issue! Please find the models here:

https://drive.google.com/drive/folders/1pGzrH67B7kQNNOOyx2jIqOp1XGfWl9KQ?usp=share_link

**Comment by CAI23sbP** [comment]
@danieldugas  Thank you for your reply!.
By the way, might i get your full code about SOADRL?
In soadrl-crowdnav (Ver: 0.0.3), it has a fragment code about SOADRL algorithm.

**Comment by CAI23sbP** [comment]
@Yuanzizizi see this reply

**Comment by CAI23sbP** [comment]
@danieldugas sorry to continuous comments

in this [drive](https://drive.google.com/drive/folders/1pGzrH67B7kQNNOOyx2jIqOp1XGfWl9KQ?usp=share_link)
it has not weight about SOADRL..
Could you check this?
![image](https://github.com/ethz-asl/navrep/assets/108871750/aea412c3-80a0-42cd-b12f-a6efaec8a665)

**Comment by danieldugas** [comment]
I checked and I do see the checkpoint, have you looked one folder higher in the directory structure?

As for the full SOADRL code, Lucia Liu is the person to ask as she has the rights to the code.

**Comment by CAI23sbP** [comment]
@danieldugas  
Oh.. my mistook. 
![Screenshot from 2024-06-06 17-57-04](https://github.com/ethz-asl/navrep/assets/108871750/733fd4e3-55ef-46fa-b355-5316ba368109)

-----
p.s. Okay, i will ask about code to her
